### ISSUE TITLE
Automate (as far as possible) a mirror of the TPP schema for testing purposes

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1104]
### Problem

In order to test that the `QueryTable` and `MappedTable` definitions in [`databuilder/backends/tpp.py`](https://github.com/opensafely-core/databuilder/blob/22ae890c46f38b5a17272eb125d20d59e8070689/databuilder/backends/tpp.py) are correctly defined we have a bunch of integration tests in [`tests/integration/backends/test_tpp.py`](https://github.com/opensafely-core/databuilder/blob/22ae890c46f38b5a17272eb125d20d59e8070689/tests/integration/backends/test_tpp.py).

These work by inserting rows into a database whose schema is intended to match that of the TPP database, and is defined using the SQLAlchemy ORM in [`tests/lib/tpp_schema.py`](https://github.com/opensafely-core/databuilder/blob/22ae890c46f38b5a17272eb125d20d59e8070689/tests/lib/tpp_schema.py).

But nothing ensures that this schema _does_ match that of the TPP database. Often, when adding a new data source, the same person defines the ehrQL table, the backend table mapping, _and_ the `tpp_schema.py` ORM table against which it is tested. So it's very easy for the same mistake (typo, misunderstanding, whatever) to make it into all three. Then the tests are all green but the job blows up when trying to run it in production.

Additionally, the ORM models in `tpp_schema.py` are much more complex than they need to be as they define a whole load of foreign key relationships between the different models. This is because they were copied directly from Cohort Extractor where they formed the primary means of constructing test fixtures. It was therefore important to be able easily to construct complex sets of interrelated objects. This need isn't so great in Data Builder as the models exist purely to test the `QueryTable` and `MappedTable` definitions.

### Proposal

Ideally we'd have some mechanism for automatically creating `tpp_schema.py` based on the actual schema of the TPP database, using something like the mechanism that powers the [Database Schema Report](https://reports.opensafely.org/reports/opensafely-tpp-database-schema/).

This wouldn't need to model any foreign-key relationships, just the column names and types. We could add a surrogate auto-increment primary key to every table (`_pk = Column(Integer, primary_key=True)` or something like that) to keep the ORM happy.

This would give us more confidence that the tests we write against that schema would be meaningful.

**Comment by evansd** [comment]
### Database Schema Report

The database schema is published here:
https://reports.opensafely.org/reports/opensafely-tpp-database-schema/

This is drawn from outputs published here:
https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/

However, it appears that only an HTML report is published, not the structured data underlying it e.g.
https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/30/output/report.html


### Questions

1. Can we get the schema in some machine readable structured format?
2. Is there an API where we can get the latest published output for a given workspace?

Assuming we can answer those questions then we can write a script which generates [`tests/lib/tpp_schema.py`](https://github.com/opensafely-core/databuilder/blob/a238c691c0d343ecca49cc9ce968736d8188e310/tests/lib/tpp_schema.py) automatically from the schema report.

And then we could have some scheduled, PR-creating Github Action (along the lines of the [external studies](https://github.com/opensafely-core/databuilder/blob/a238c691c0d343ecca49cc9ce968736d8188e310/.github/workflows/update-external-studies.yml) one) which automatically opens a PR whenever the schema changes.

**Comment by iaindillingham** [comment]
The `query` action in that study writes _output/rows.csv_, which contains the schema. Like the report, it's moderately sensitive, so can -- in principle -- be released. Running that study locally will give a dummy schema. (Using it to address this issue just moves the problem from Data Builder to the study, though.)

I've requested the CSV is released; when it is, I'll publish it. It will then have a public URL on OS Jobs. There isn't a URL for the latest published outputs (but there is for the latest released outputs).

**Comment by evansd** [comment]
The schema is now published here:
https://jobs.opensafely.org/datalab/opensafely-internal/tpp-database-schema/outputs/38/output/rows.csv

There isn't currently a direct way of getting the latest published output for a workspace so we might need to scrape that from the workspace page or something like that.
