### ISSUE TITLE
Include "table helper" methods in documentation

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1185]
Some ehrQL tables have "helper methods" defined for commonly used queries. For example:
https://github.com/opensafely-core/databuilder/blob/3ea4c88a9c6a68a71e94b326b76128a34ae39b56/databuilder/contracts/universal.py#L32-L41

https://github.com/opensafely-core/databuilder/blob/3ea4c88a9c6a68a71e94b326b76128a34ae39b56/databuilder/tables/beta/tpp.py#L63-L80

We should extract metadata for these in [docs.schemas](https://github.com/opensafely-core/databuilder/blob/3ea4c88a9c6a68a71e94b326b76128a34ae39b56/databuilder/docs/schemas.py) and display them as part of the documentation for that table.

We should extract their docstring, their argument signature (include types where these are supplied), and ideally the method definition itself. We might want to have the method definition hidden by default in the docs, but making it easy for users to see how these are defined seems worthwhile.

We might want to consider replacing `self` with the table name itself when we display the method definition in the docs as that might be clearer to the user while being semantically equivalent.

This ticket depends on first completing:

 * https://github.com/opensafely-core/databuilder/issues/1184

**Comment by StevenMaude** [comment]
@evansd: is there anything more to do for this issue, following the merge of #1305, or can it be closed?

(Reading it, I don't think so, but don't want to close it in case there is!)

**Comment by evansd** [comment]
Oh yes, I meant to close this. Thanks!
