### ISSUE TITLE
Move common tables out of `tpp` namespace

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1237]
In preparation for adding support for the OpenSAFELY EMIS backend, we should move common tables out of the `tpp` namespace.

We should:

- [x] move `patients,` `clinical_events`, `medications`, `ons_deaths` from `tables.beta.tpp` into `tables.beta.core`
- [x] update `tables.beta.tpp` so that it imports these table definitions from `tables.beta.core`
- [x] Add `tables.beta.core` to the [list of schemas](https://github.com/opensafely-core/ehrql/blob/919ff233d85e6c245824d28ba99bc6f4a4318fe7/ehrql/backends/tpp.py#L12) implemented by the TPP backend
- [x] update all documentation on the wiki

Acceptance criteria:

- [x] a user can run through the updated [instructions about running ehrQL in sandbox mode](https://github.com/opensafely-core/ehrql/wiki/running-ehrql#sandbox-mode) (they will not need to make changes to their dummy data)

**Comment by StevenMaude** [comment]
#1241 is now merged, so we can update what we advise users to do.

Do we want to encourage the use of `ehrql.tables.beta.core` over `ehrql.tables.beta.tpp`?

So if you want, let's say, the `patients` and `practice_registration` tables, is this our suggested way of doing so:

```
from ehrql.tables.beta.core import patients
from ehrql.tables.beta.tpp import practice_registrations
```

Note that, at the moment, the following still works, which ensures nothing breaks:

```
from ehrql.tables.beta.tpp import patients, practice_registrations
```

**Comment by StevenMaude** [comment]
Have updated the wiki, which may be enough to close the rest of this issue.
