### ISSUE TITLE
Possible confusion over contents of `APCS_Der.Spell_Primary_Diagnosis`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1248]
Previous [investigation](https://github.com/opensafely-core/ehrql/issues/1066#issuecomment-1441614133) by @milanwiedemann suggests that the `APCS_Der.Spell_Primary_Diagnosis` column can contain multiple diagnosis codes, separate by semi-colons.

But the schema description says that this column has a maximum length of 5, which doesn't seem big enough if this column is expected to contain multiple diagnosis codes:
https://reports.opensafely.org/reports/opensafely-tpp-database-schema/#APCS_Der

ICD-10 codes can be as short as 2 characters, so technically you could fit two of them plus a separator. But if the intention is that this column can contain multiple codes then this seems far too small.

We should get to the bottom of what's going on here, as possibly this indicates some confusion elsewhere.

**Comment by StevenMaude** [comment]
The original intent, at least, seems to be that `der_diagnosis_all` can contain multiple codes:

> The field "der_diagnosis_all" is a concatenation of all diagnosis fields in all
episodes within the spell.

https://www.england.nhs.uk/wp-content/uploads/2018/06/04-b-pb-04-07-2018-ebi-consultation-document.pdf

**Comment by evansd** [comment]
@StevenMaude Yes, that's `Der_Diagnosis_All` which is different from `Spell_Primary_Diagnosis`.

Further investigation confirms:

 * the schema description is correct and we never have more than 5 characters in this column:
   ```sql
   SELECT MAX(LEN(Spell_Primary_Diagnosis)) FROM APCS_Der;
   -- 5
   ```
 * the character `;` occurs nowhere in this column:
   ```sql
   SELECT COUNT(*) FROM APCS_Der WHERE Spell_Primary_Diagnosis LIKE '%;%';
   -- 0
   ```

@milanwiedemann Do you remember what you saw that made you think there were multiple diagnoses here? It's always possible that something has changed since the time you checked, but it seems unlikely.

**Comment by milanwiedemann** [comment]
I vaguely remember seeing something like this `A1;B1;C1`

**Comment by evansd** [comment]
I think the next steps here are:

1. We should add a singular `primary_diagnosis` field to the `hospitalisations` table:
   https://github.com/opensafely-core/ehrql/blob/2e09a533261a3d3ebdc059afcc46d56f56221bec/ehrql/tables/beta/tpp.py#L191-L201
   Along the lines of:
   ```py
   primary_diagnosis = Series(ICD10Code)
   ```
   Plus the appropriate mapping in `TPPBackend`.

2. We should add a `description` attribute to the `primary_diagnoses` field explaining that this field only ever contains a single code and is now deprecated in favour of the `primary_diagnosis` field.

3. When we come to make the non-beta version of this schema would should remove this field. (Alternatively we could use Github search to find all uses of it and manually update, but that's probably more effort than it's worth.)
