### ISSUE TITLE
Dummy data should not treat "values used" as equivalent to categories

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1266]
## Context

As part of dummy data generation the `query_info` module finds every comparison made with every column used in a dataset definition and records them in a `values_used` set for each column:
https://github.com/opensafely-core/ehrql/blob/c58fbd8bf3e35983dd98944d8ea7222c143f1fc3/ehrql/dummy_data/query_info.py#L41-L44

This is all well and good, but when we come to generate dummy data we treat this `values_used` set just as if it were a categorical constraint 
https://github.com/opensafely-core/ehrql/blob/c58fbd8bf3e35983dd98944d8ea7222c143f1fc3/ehrql/dummy_data/query_info.py#L47-L52

And we end up saying that only these values can appear in the column.
https://github.com/opensafely-core/ehrql/blob/c58fbd8bf3e35983dd98944d8ea7222c143f1fc3/ehrql/dummy_data/generator.py#L212-L214

This is particularly silly when only a single comparison has been made because then we only have one value to work with so we just use it every time (see #1265).

I think the logic we want is:
 * If there is a categorical constraint on the column then that determines the set of valid values and we should always choose one of those.
 * Otherwise, if there are `values_used` then we should randomly choose one of these _or_ choose to fall through to whatever random generation approach we would have used otherwise.
 * The probability distribution according to which we choose to fall through or not should depend on the number of values we have. I don't know the exact logic we want here, but clearly if we've only got one value then we want to be falling through certainly more than 50% of the time. Whereas if we've got 30 values then I think we want to be mostly using those and only occasionally falling through.

## Implementation notes

Dave's sketch of how this could work:

 * Get rid of the `choices` property on `ColumnInfo`.

 * Rename the `values_used` attribute to `_values_used` to make it internal.

 * Add a public `values_used` property which returns the sorted values:
   ```py
   @cached_property
   def values_used(self):
       return sorted(self._values_used)
   ```
   (It's worth caching this because we'll be accessing this list frequently.)

 * The first thing that `DummyPatientGenerator.get_random_value()` should do is check for a categorical constraint:
   ```py
   if cat_constraint := column_info.get_constraint(Constraint.Categorical):
       return self.rnd.choice(cat_constraint.values)
   ```

 * The next thing is to check whether `column_info.values_used` is empty, and if it's not we need to decide whether we're going to use one of these values or not. @inglesp suggested doing this with probability `1/(N+1)` for `N` values, so something like (untested code):
   ```py
   if column_info.values_used:
       if self.rnd.randint(0, len(column_info.values_used)) != 0:
           return self.rnd.choice(column_info.values_used)
   ```

 * Finally we fall back to the `if/elif` chain based on `column_info.type`.

 * The dummy data system has 100% unit test coverage so it supports a fast testing cycle while working on it:
   ```
   pytest --cov ehrql.dummy_data --cov-report=html tests/unit/dummy_data/
   ```

**Comment by sebbacon** [comment]
This makes me wonder if/when we should start a page of documentation about "how dummy data works" to aid principle of least surprise for researchers?
