### ISSUE TITLE
Commits from "update" workflows aren't signed 

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/ehrql#1274]
Not sure if this is a serious problem. However, if a goal/policy is to sign all our commits, then we should be doing so.

Example unverified commit: 70e658b0bada5ff65c3ee74c869926b9aa4aa77a

Relevant information:

https://github.com/actions/runner/issues/667
https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps/
https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c

**Comment by evansd** [comment]
I believe this is closed by #1275
