### ISSUE TITLE
Work out how to make type information available to local code editors

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1297]
Even without having put a lot of explicit effort into supporting it (and we [do plan](https://github.com/opensafely-core/ehrql/issues/506) to put this effort it at some point), VSCode gives surprisingly helpful auto-complete and type checking behaviour for ehrQL.

However this only works if ehrQL is installed locally as a Python package; just having the ehrQL docker image on your machine is insufficient. But installing ehrQL locally is awkward and faffy and it's easy for the version to get out of sync with the docker image (see [this Slack thread](https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1685467065113579)).

We need to do _something_ here to make this all work, but I've no idea what. More research is needed.

**Comment by rebkwok** [comment]
Closing in favour of:
https://github.com/opensafely-core/research-template-docker/issues/84, which updates the way ehrql code is pulled in in Codespaces/devcontainers
And with the plan to replace that eventually with the vscode extension which would work for both codespaces and local: https://github.com/opensafely-core/opensafely-vscode/issues/14 (
