### ISSUE TITLE
Expose `Appointment.Status`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1308]
It looks as though [_Project #152: Digital access to primary care for older people during COVID_][1] would benefit from access to `Appointment.Status` through ehrQL. Because of #1307, not all values of this column will be present.

Right, how do I do that, then?

Add a property to the `EventFrame`. Don't forget to add constraints; these are used by the dummy-data generator and by the documentation.

https://github.com/opensafely-core/ehrql/blob/b453a7ed1691ba12c31107aa8f7fbeb177b3515a/ehrql/tables/beta/tpp.py#L202-L205

Update the query. Don't forget to join to [the `DataDictionary` table][2] to get human-readable status descriptions rather than status codes. (These are the values of `Constraint.Categorical`, above.)

https://github.com/opensafely-core/ehrql/blob/b453a7ed1691ba12c31107aa8f7fbeb177b3515a/ehrql/backends/tpp.py#L208-L220

Run the tests. Fix the tests. Remember [Conventional Commits][3].

[1]: https://www.opensafely.org/approved-projects/#project-152
[2]: https://reports.opensafely.org/reports/opensafely-tpp-database-schema/#DataDictionary
[3]: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by milanwiedemann** [comment]
@iaindillingham currently I'm hard coding the appointment status variables and I dont think that's a good idea? you mentioned joining to another table in the issue but I'm not sure what you I know what you mean?

> Don't forget to join to [the DataDictionary table](https://reports.opensafely.org/reports/opensafely-tpp-database-schema/#DataDictionary) to get human-readable status descriptions rather than status codes. (These are the values of Constraint.Categorical, above.)

**Comment by iaindillingham** [comment]
`Appointment.Status` is an integer that maps to a human-readable description. I think that human-readable description is stored in `DataDictionary.Description`. To access it, we'd join `Appointment` to a table derived from `DataDictionary`. Consequently, the query in the `QueryTable` would look something like:

```sql
SELECT DISTINCT
    Appointment_ID AS appointment_id,
    Patient_ID AS patient_id,
    CAST(BookedDate AS date) AS booked_date,
    CAST(StartDate AS date) AS start_date,
    Description AS status
FROM Appointment LEFT JOIN (
    SELECT
        CAST(Code AS INT) AS Code,
        Description
    FROM DataDictionary
    WHERE Table = 'Appointment'
) AS t ON Status = t.Code
```

Notice that whilst the database column `Appointment.Status` is an integer, the ehrQL column `appointments.status` is a string. ehrQL has taken care of the mapping.
