### ISSUE TITLE
Make the documentation deployment trigger workflow more robust, if possible

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/ehrql#1316]
This either has stopped working completely or has had a one-off failure (found on merge of #1315).

**Comment by StevenMaude** [comment]
Actually, it seems to have appeared now following a subsequent run of the triggering workflow:

"Failing" trigger workflow: https://github.com/opensafely-core/ehrql/actions/runs/5255241935/jobs/9494896335
Working trigger workflow: https://github.com/opensafely-core/ehrql/actions/runs/5255768269/jobs/9496122058

In both cases, the workflow in this repository completed successfully.

In the "failing" case, the associated workflow in `opensafely/documentation` did not run. So it seems like the `workflow_run` trigger failed in some way.

Like many things GitHub Actions, this is potentially tricky to debug, complicated by two repositories being involved.

There are a number of possible points of failure:

* error in the trigger workflow in this repository
* erorr in the publish documentation in `opensafely/documentation` workflow
* failure to pass the `workflow_run` trigger to the publish documentation workflow by GitHub Actions (which is out of our control)
* expiry of secret tokens in either one of these workflows
* Cloudflare Pages failing to build
* perhaps the commit which triggers the workflow is somehow not being available to the documentation build at the time the documentation build happens (I don't imagine this should happen, but maybe it does?)

Possible false positive:

* browser caching retaining an old version of a page?

Other thoughts:

* the multirepo plugin doesn't give any way of displaying commit ID for debugging

*However*, we know that:

* the actual workflows currently work end-to-end, from the subsequently successful workflow.

**Comment by inglesp** [comment]
Thanks for the writeup @StevenMaude.  I'm going to close this as we've only seen this once.
