### ISSUE TITLE
Better format the output of `dump-dataset-sql`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1319]
The output of `dump-dataset-sql` is reasonably legible, but could be more so. I've been piping it to [SQLFluff](https://sqlfluff.com/), for example:

```sh
opensafely exec ehrql:v0 dump-dataset-sql $dataset_definition | sqlfluff fix -f - > output/dataset.sql
```

Whilst SQLFluff is good, it's not great: It's slow (see below) and we'd have to think about suitable configuration, which would also be query-engine dependant. This configuration has worked reasonably well for me, so far:

```cfg
[sqlfluff]
dialect = tsql
exclude_rules = capitalisation.identifiers
max_line_length = 88
```

However, I'm sure other formatters are available.

---

> Whilst SQLFluff is good, it's not great: It's slow

How slow is slow? SQL dumped from the following dataset definition took four seconds fix:

```py
from datetime import date

from ehrql import Dataset
from ehrql.tables.beta.tpp import open_prompt

index_date = open_prompt.consultation_date.minimum_for_patient()
offset_from_index_date = (open_prompt.consultation_date - index_date).days

dataset = Dataset()
dataset.define_population(open_prompt.exists_for_patient())

dataset.index_date = index_date

dataset.date_at_offset_0 = (
    open_prompt.where(offset_from_index_date == 0)
    .sort_by(open_prompt.consultation_id)
    .last_for_patient()
    .consultation_date
)
```

**Comment by inglesp** [comment]
Not a priority now.
