### ISSUE TITLE
Make ehrQL citable

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1320]
Whilst a paper adds [a flag](https://youtu.be/_9W1zTEuKLY) to the literature, the flag can mean "I used these ideas" rather than "I used this software". Arguably, ehrQL would benefit from both. We could achieve the second meaning by adding a `CITATION.cff` file to this repo. From [the Citation File Format website](https://citation-file-format.github.io/):

> `CITATION.cff` files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.

Before we go ahead and add such a file, however, we should check with someone who knows about publishing papers that, for the journals we're thinking about publishing the paper in, such a file wouldn't "count" as a publication.

**Comment by inglesp** [comment]
Not a priority.
