### ISSUE TITLE
Improve table schemas documentation

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1340]
The [schema docs](https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/) should tell users all that we know about the data in each table, including:

* what it contains
* where it comes from
* warnings about known issues with the data
* whether it is refreshed regularly (and if not, we should link to the database history report)
* links to any external documentation
* links to any short data reports
* a description of the contents of each column

Documentation can be cribbed from [existing data sources](https://docs.opensafely.org/data-sources/) docs, but we may have to search Slack, GH, and the cohort-extractor codebase for other information.#

This is also the opportunity to consider whether tables and columns are correctly named.

We'll divide up the work across the whole data team, and with issues for each table (or group of tables).

- [ ] #1371 
- [x] #1372
- [x] #1373
- [ ] #1374
- [ ] #1375
- [ ] #1376
- [ ] #1377
- [x] #1378
- [ ] #1379
- [x] #1380
- [x] #1381
- [x] #1382
- [ ] #1383
- [ ] #1384
- [ ] #1385

**Comment by iaindillingham** [comment]
@CLStables

**Comment by sebbacon** [comment]
Some documentation about practice registrations and appointments to crib [here](https://bennettoxford.slack.com/archives/C02HJTL065A/p1689327065988359)

**Comment by CLStables** [comment]
I can't figure out which table eFI is in, but whichever one it is should include useful metadata from [this thread](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1690282965908879)

**Comment by iaindillingham** [comment]
The eFI is accessed through `patients.with_these_decision_support_values` in cohort-extractor. This function resolves to `cohortextractor.tpp_backend.patients_with_these_decision_support_values` and [these SQL queries][1] against the `DecisionSupportValue` table. The [OpenSAFELY-TPP database schema][2] report doesn't reference this table; however, `SELECT COUNT(*) FROM DecisionSupportValue` on L2 returns roughly 29,000 rows.

[1]: https://github.com/opensafely-core/cohort-extractor/blob/v1.86.2/cohortextractor/tpp_backend.py#L1341-L1382
[2]: https://reports.opensafely.org/reports/opensafely-tpp-database-schema/

**Comment by inglesp** [comment]
Closing, as we've got individual tickets for each table.
