### ISSUE TITLE
Handle duplicates in `ons_deaths`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1359]
The `ons_deaths` table contains duplicates, and so is an `EventFrame`. However, as @hendersonad [observed][1], this can be confusing.

[We discussed][2]:

* The SQL approach: Modifying `TPPBackend.ons_deaths` (i.e. replacing the `MappedTable` with a `QueryTable`)
* The ehrQL approach: Renaming `ons_deaths` to `ons_deaths_raw` and creating an `ons_deaths` that handled duplicates

I think we decided on the second option, as it's easier for a researcher to reason in ehrQL than in SQL. (Eventually, there may be non-SQL backends; it's easier for a researcher to reason in on language than in several languages.)

[1]: https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1687966907932439?thread_ts=1687434431.458539&cid=C04DVD1UQC9
[2]: https://bennettoxford.slack.com/archives/C03FB777L1M/p1678790050286699

**Comment by iaindillingham** [comment]
There's more discussion in [this Slack thread][1]. @inglesp suggested making either `ons_deaths.first_for_patient` or `ons_deaths.last_for_patient` a noop, having first sorted `ons_deaths`. We could then convert it from an `EventFrame` to a `PatientFrame` later.

[1]: https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1695291953108589

**Comment by iaindillingham** [comment]
Changes to code, tests, and docs:

- [ ] Rename `ons_deaths` ehrQL table to `ons_deaths_raw` (`ehrql.tables.beta.core`)
- [ ] Rename `TPPBackend.ons_deaths` backend table to `TPPBackend.ons_deaths_raw` (`ehrql.backends.tpp`)[^1]
- [ ] Create `ons_deaths` ehrQL table (`PatientFrame`) and an `TPPBackend.ons_deaths` backend table (`QueryTable` using [`ROW_NUMBER`](https://learn.microsoft.com/en-us/sql/t-sql/functions/row-number-transact-sql?view=sql-server-ver16))
- [ ] Search for repos with code that will need to be updated. Is it worth opening (draft) PRs?
- [ ] Announce the change in [Platform news](https://www.opensafely.org/changelog/)

[^1]: This will remain an instance of `MappedTable`.

**Comment by milanwiedemann** [comment]
A quick search on github indicates that the original ons_deaths (EventFrame) was used in these dataset definitions:

- [ ] [isaric-exploration/analysis/dataset_definition_sus.py](https://github.com/opensafely/isaric-exploration/blob/4ed4802bb22659a76d358cc6768817f69689f43b/analysis/dataset_definition_sus.py#L238-L244)
- [ ] [isaric-exploration/analysis/dataset_definition_isaric.py](https://github.com/opensafely/isaric-exploration/blob/4ed4802bb22659a76d358cc6768817f69689f43b/analysis/dataset_definition_isaric.py#L290-L293)
- [ ] [openprompt_health_utilisation/analysis/covariates.py](https://github.com/opensafely/openprompt_health_utilisation/blob/745ac553c9fb99101d5e5b26bc76348895dfa253/analysis/covariates.py#L69-L70)
- [ ] [vaccine-counts/analysis/dataset_definition_fixed.py](https://github.com/opensafely/vaccine-counts/blob/ecbf380c2825b9a08d76eb8e8368f5c286fd9064/analysis/dataset_definition_fixed.py#L28)
- [ ] [shielding-evaluation/analysis/databuilder_definition.py](https://github.com/opensafely/shielding-evaluation/blob/54c81bcd0887a766edd200812c0242b397f7b73e/analysis/databuilder_definition.py#L124-L131)
- [ ] [early-inflammatory-arthritis/analysis/dataset_definition.py](https://github.com/opensafely/early-inflammatory-arthritis/blob/91e056758a6aeed78cd2c29d44d7d2278cc831b7/analysis/dataset_definition.py#L80)
- [ ] [cis-pop-validation-ehrql/analysis/dataset_definition.py](https://github.com/opensafely/cis-pop-validation-ehrql/blob/cce4f0bfaffa5370b00f847fbcfe742c7a13aeeb/analysis/dataset_definition.py#L73)
- [ ] [openprompt-vaccine-long-covid/analysis/dataset_definition_longcovid_prevaccine.py](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/eebd4c0e6dc739ad63d00489aa2e0457a22dbec0/analysis/dataset_definition_longcovid_prevaccine.py#L100-L101)
- [ ] [end-of-life-carequality/analysis/ehrql/dataset_definition_ehrql_example.py](https://github.com/opensafely/end-of-life-carequality/blob/9f2a605349d0539dbb9fb760ac180e40e0bb9109/analysis/ehrql/dataset_definition_ehrql_example.py#L36)
- [ ] [end-of-life-carequality/analysis/os_reports/dataset_definition_os_reports.py](https://github.com/opensafely/end-of-life-carequality/blob/9f2a605349d0539dbb9fb760ac180e40e0bb9109/analysis/os_reports/dataset_definition_os_reports.py#L35)
- [ ] [vte-diagnoses-and-deaths/analysis/dataset_definition.py](https://github.com/opensafely/vte-diagnoses-and-deaths/blob/72f97de06a678ee8ddfeaae32a5413c22c02a389/analysis/dataset_definition.py#L53-L54)
- [ ] [openprompt-vaccine-long-covid/analysis/datasets.py](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/eebd4c0e6dc739ad63d00489aa2e0457a22dbec0/analysis/datasets.py#L68-L69)
