### ISSUE TITLE
Add helper method for querying multiple `cause_of_death` fields

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1363]
The `ons_deaths` table records multiple causes of death in separate, numbered fields (apparently 15 is the most number of things you can die of):
https://github.com/opensafely-core/ehrql/blob/27f548e744abd259fae4bb2d36070cd988b3c6a1/ehrql/tables/beta/core.py#L70-L86

At some stage we'd like to have proper support for [multi-valued columns](https://github.com/opensafely-core/ehrql/issues/574) in ehrQL, but until we do it would be helpful to provide a method for querying across all these fields in one go. I'm imagining something like:
```py
import operator
from functools import reduce

...

def any_cause_of_death_is_in(self, codelist):
    conditions = [
        getattr(self, f"cause_of_death_{i:02d}").is_in(codelist)
        for i in range(1, 16)
    ]
    return reduce(operator.or_, conditions)
```

To test this we should first move the misplaced `test_patients_age_on` function from [`tests/integration/tables/beta/test_core.py`](https://github.com/opensafely-core/ehrql/blob/27f548e744abd259fae4bb2d36070cd988b3c6a1/tests/integration/tables/beta/test_tpp.py#L7-L29) to `tests/integration/tables/beta/test_core.py` and replace references to `tpp.patients` with `core.patients`.

Then we can add a `test_ons_deaths_any_cause_of_death_is_in` function along similar lines.

**Comment by wjchulme** [comment]
Would it be much extra work to make this available for generic sets of columns of the form `foo_1, foo_2, foo_3, ...`, or even arbitrarily named columns of the same form, something like `symptom_fever, symptom_cough, symptom_anosmia, symptom_headache, ...`?

I can easily see how the answer to this question might be "yes, by orders of magnitude" so don't let this hold anything up. But these types of across column queries are well-supported in other languages and would likely get a lot of use in ehrQL too. It would also make it less likely that people would extract all columns to L3 for downstream processing in R / stata, which helps minimise disclosure risk.

**Comment by iaindillingham** [comment]
`core.ons_deaths` is an `EventFrame`. Although that's unexpected (#1359), we could

```py
derived_ons_deaths = core.ons_deaths.sort_by(core.ons_deaths.date).first_for_patient()
```

However, the call to the `.first_for_patient()` method takes us to

https://github.com/opensafely-core/ehrql/blob/7115972c780e79c57441e7e006a2e708c1770d6b/ehrql/query_language.py#L706-L716

which returns properties but not methods. Consequently, whilst there will be a `core.ons_deaths.any_cause_of_death_is_in()` method, there won't be a `derived_ons_deaths.any_cause_of_death_is_in()` method.

Sadly,

```py
core.ons_deaths.any_cause_of_death_is_in(...).exists_for_patient()`
```

doesn't exist. (That is, `BoolEventSeries.exists_for_patient()` doesn't exist.) So, to use this helper method, we'd have to

```py
core.ons_deaths.any_cause_of_death_is_in(...).count_distinct_for_patient() > 0
```

which is a bit so-so. Sure, we don't have to query 15 series individually, but what are we counting and why?

#1366 contains the helper method and a test. However, I think it may be more helpful to address #1359 first.

**Comment by iaindillingham** [comment]
In answer to your question, @wjchulme, I'm afraid I don't know. However, I think it would be best to address this specific issue first.

**Comment by iaindillingham** [comment]
Would you be happy if I closed this issue and deleted the PR, @evansd?

**Comment by iaindillingham** [comment]
Closing, because everything is more complicated than you think 🤖
