### ISSUE TITLE
Batch final insert statements in `OpenCoronaTempTables` 

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/ehrql#1445]
In order to address the [issue ](https://docs.google.com/document/d/1_0lAkLxMl4Hgf1W4MsMg1reIgOX5VSdnLxiZtcbpRjc/edit )of an over-full transaction log on `OpenCoronaTempTables` we may wish to reduce the overall maximum size of a given transaction operating in this database whilst running the final steps of getting results where results are written to a table in order to allow jobs to reconnect and get their results in event of a failed database connection. 

```sql
-- create the results table from a select into as we do currently
BEGIN TRANSACTION
SELECT * 
INTO opencoronatemptables..results_1234 
FROM [... right old big query with loads of joins to #tmp tables etc...] 
WHERE 1=0
COMMIT

-- put a Clustered Index on this table as it'll always be 1RPP
ALTER TABLE opencoronatemptables..results_1234 ALTER COLUMN patient_id INT NOT NULL;
CREATE CLUSTERED INDEX ix_patient_id ON opencoronatemptables..results_1234(Patient_id);

--do insert in batches
DECLARE @rows_inserted INT
WHILE (1=1)
BEGIN
  BEGIN TRANSACTION
    INSERT opencoronatemptables..results_1234
    SELECT  TOP (10000) * 
    FROM [... right old big query with loads of joins to #tmp tables etc...] as X 
    WHERE NOT EXISTS(
          SELECT y.patient_id 
          FROM opencoronatemptables..results_1234 y 
          WHERE y.patient_id = x.patient_id)
    SELECT @rows_inserted = @@rowcount
  COMMIT
  IF @rows_inserted = 0
    BREAK
END
```

This may have some negative effects in overall database server load and job throughput but will reduce the amount of transaction log usage at a given level of database job concurrency.

**Comment by evansd** [comment]
Closing in favour of:
https://github.com/opensafely-core/ehrql/pull/1529
