### ISSUE TITLE
Docker images should be tagged with the git commit

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1484]
This is useful for debugging. We do this when building images for other services e.g.
https://github.com/opensafely-core/job-server/blob/62bb8ab679bc19731291fe8c10f513c8dfa3ea99/docker/Dockerfile#L179-L184
```Dockerfile
# finally, tag with build information. These will change regularly, therefore
# we do them as the last action.
ARG BUILD_DATE=unknown
LABEL org.opencontainers.image.created=$BUILD_DATE
ARG GITREF=unknown
LABEL org.opencontainers.image.revision=$GITREF
```

It's not _essential_ as the images are tagged with version, for which there is a corresponding git tag. But it would be nice to have an immutable identifier here and nice to have things consistent across our images.

**Comment by StevenMaude** [comment]
This should be an actual image tag.
