### ISSUE TITLE
Expose TPP's CodedEventRange table

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1491]
`CodedEventRange` is a table which can be joined onto `CodedEvent` to gives extra information about numeric values -- specifically: lower bound, upper bound, and comparator.

It is exposed in cohort-extractor via [`patients.comparator_from`](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.comparator_from).

The simplest approach would be to update [the SQL used to build the `clinical_events` table](https://github.com/opensafely-core/ehrql/blob/4770ec6f1d387c9aead150f30dfdba9d8c94e208/ehrql/backends/tpp.py#L88-L106) to include a join on `CodedEventRange`, and then to add the new fields to [the table definition](https://github.com/opensafely-core/ehrql/blob/4770ec6f1d387c9aead150f30dfdba9d8c94e208/ehrql/tables/beta/tpp.py#L33-L38).  However, we would need to be satisfied that doing this wouldn't significantly affect performance of queries that don't use the joined table.

An alternative would be to add machinery to only include the join when necessary.

As such, the first task will be to measure the performance of typical queries with and without the join, to determine the impact of the join.

**Comment by LFISHER7** [comment]
A note for when this is done. [This paper](https://doi.org/10.12688/wellcomeopenres.19858.1), describing the use of comparators for key pathology tests is a useful reference to include in the docs. @HelenCEBM or I can suggest accompanying text

**Comment by Jongmassey** [comment]
>As such, the first task will be to measure the performance of typical queries with and without the join, to determine the impact of the join. 

Feels like a SQL Runner job that captures some timings is the best way to get real-world performance numbers on this. Do you agree @inglesp  ?

**Comment by inglesp** [comment]
Yes, assuming SQL Runner can tell us this stuff!

**Comment by Jongmassey** [comment]
https://github.com/opensafely-core/sqlrunner/blob/main/sqlrunner/main.py#L57-L59

I'm assuming that we can use the timestamps of these two log statements for this purpose. Failing that, I could modify sqlrunner to make use of the statistics provided by the various `SET STATISTICS` options that are used in `ehrQL` and `cohort-extractor`

**Comment by Jongmassey** [comment]
results from [first run of perf eval job](https://jobs.opensafely.org/opensafely-internal/coded-event-performance-evaluation/21483/)
| action | start/finish executing sql log delta (ms) | duration_ms | exec_cpu_ms | exec_elapsed_ms | parse_cpu_ms | parse_elapsed_ms |
| --- | --- | --- | --- | --- | --- | --- |
| clinical_events_with_codelist_ctv3 | 94 | 0 | 0 | 0 | 0 | 5 |
| clinical_events_with_codelist_snomed | 82 | 0 | 0 | 0 | 7 | 7 |
| comparator_from_with_codelist_ctv3 | 45,731 | 45 | 0 | 0 | 23,235 | 27,334 |
| comparator_from_with_codelist_snomed | 43,993 | 43 | 0 | 0 | 16,118 | 16,324 |

**Comment by Jongmassey** [comment]
Thanks for that Dave, the numbers didn't quite look right to me. I think we can largely disregard the parse numbers as this was the first run of a query it won't have encountered before cf a query that's run on a regular basis.

A context manager approach does indeed seem like the right approach, I'll take a look

**Comment by Jongmassey** [comment]
As I suspected, after re-running the parse times for the second pair of queries also reduced to zero. Wall-clock times are 86, 87, 15609, 15346 respectively so there's still clearly a big performance hit
