### ISSUE TITLE
Document that appointments never move between practices

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1496]
In [this Slack thread][1], @sebbacon writes

> On the appointments issue: consultations do move; appointments never move. Because appointments are administrative data related to (e.g.) scheduling. However, if you want to research DNAs, that's hard, because they are recorded as appointments

See also [_Defining patient populations with censoring_][2].

We should update the documentation for the `appointments` table (and, if we reference it in the future, the `Consultation` table). Before we do, however, it would be good to have a reference for the assertion that appointments never move between practices.

[1]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1689327065988359
[2]: https://docs.google.com/document/d/1Gk66X_jNmm2g1ffr3jlfi_XzKlYcxq1Ibc-8DS0NoQE/edit?pli=1#heading=h.773zpunqw7st

**Comment by sebbacon** [comment]
(The source was Chris Bates, in a phone call)

**Comment by sebbacon** [comment]
Just to clarify - are you awaiting another (better) reference? Because I think that's the best we're likely to get!

**Comment by iaindillingham** [comment]
I'm not - thank you for clarifying, though. The issue's on the backlog.
