### ISSUE TITLE
Update DOCS_WRITE_TOKEN

### ISSUE THREAD

**Issue by madwort** [opensafely-core/ehrql#1516]
@madwort had a notification on 22 Aug that the fine-grained access token named `ehrql DOCS_WRITE_TOKEN` attached to their account will expire on 29 Aug. Although there is a "regenerate token link", it would be better if the Data team managed this token.

**Comment by iaindillingham** [comment]
More information in [this Slack thread][1].

* Create a fine-grained PAT on your account. It needs to access opensafely/documentation; read access to metadata; read and write access to actions and code.
* In opensafely-core/ehrql go to Settings > Secrets > Actions do something
* In opensafely-core go to Settings > Secrets > Actions do something

People who currently have permission to "do something":

- Ben B.C.
- Dave
- George
- Hilary
- Lucy
- Peter
- Seb
- Simon
- Tom W.

[1]: https://bennettoxford.slack.com/archives/C03FB777L1M/p1692785895624139

**Comment by inglesp** [comment]
I can't work out how to grant write access to code.  It doesn't appear in this list:


![Image](https://github.com/opensafely-core/ehrql/assets/28734/8c55101a-6c8c-4d58-9286-41ed5a03cf9f)

And nor can I see any reference in [the docs](https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28).

**Comment by inglesp** [comment]
We wanted "Contents".
