### ISSUE TITLE
Allow user to change size of dummy population

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1568]
This is the most basic level of customisation we can provide, and we've had several requests for this already.

In terms of mechanics we need to get the desired value passed in as the `population_size` keyword argument here:
https://github.com/opensafely-core/ehrql/blob/74642c268f878be48bc23e385b9edf74d267e9d5/ehrql/main.py#L106

And here:
https://github.com/opensafely-core/ehrql/blob/74642c268f878be48bc23e385b9edf74d267e9d5/ehrql/main.py#L117-L118

As to how the user sets this there are various ways we could do this but I'm leaning towards a method on `Dataset` like:
```py
def configure_dummy_data(self, *, population_size=None):
    ...
```

The argument needs to be keyword-only so we don't risk users passing it positionally and making it harder to change the API.

We'll also need to think about how this interacts with measures. The same argument will need passing here:
https://github.com/opensafely-core/ehrql/blob/74642c268f878be48bc23e385b9edf74d267e9d5/ehrql/main.py#L261

And then threading through to the `DummyDataGenerator` here:
https://github.com/opensafely-core/ehrql/blob/74642c268f878be48bc23e385b9edf74d267e9d5/ehrql/measures/dummy_data.py#L16-L23

(Aside: we may need to something cleverer with the measures dummy data generator here e.g. making sure that the population is equally distributed among the intervals.)

**Comment by inglesp** [comment]
Closed by #1587.
