### ISSUE TITLE
Add a function for instantiating objects of class `Dataset`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1574]
When watching Rose work through the ehrQL tutorial recently, I realized just how confusing

```py
dataset = Dataset()
```

must be. As an exercise, try to describe what's happening above, without using the words _instantiate_, _object_, or _class_ (Alternatively, try to describe this issue's title.)

We know, anecdotally, that ehrQL seems to be more Python-like than cohort-extractor. Perhaps we could make it less so with

```py
dataset = create_dataset()
```

I think @inglesp raised this issue on Slack awhile back. I also think that there was a brief discussion about whether the verb should be "create", "make", or whatever. I don't think it matters; but the ehrQL tutorial instructs a user to [_Create the dataset_](https://docs.opensafely.org/ehrql/tutorial/writing-a-dataset-definition/#create-the-dataset).

**Comment by evansd** [comment]
I'm in favour of this. Here's the [original thread](https://bennettoxford.slack.com/archives/C03FB777L1M/p1682605407408419) where a few options were discussed including:
 * `new_dataset()`
 * `make_new_dataset()`
 * `make_empty_dataset()`
 * `create_empty_dataset()`

I think `create_dataset()` is my preference so far though.

**Comment by evansd** [comment]
For parity we should also define a `create_measures()` function.

**Comment by inglesp** [comment]
> I think `create_dataset()` is my preference so far though.

Mine too.  I like the verb + noun, and I like the succinctness.

**Comment by iaindillingham** [comment]
Note to self: don't forget to update the ehrQL tutorial.
