### ISSUE TITLE
Restructure the language reference

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1623]
The structure of the language reference could better reflect how a user encounters the language in their dataset definitions:

- Dataset
    - create_dataset
    - Dataset
- Frames
- Series
- Date Arithmetic
- Codelists
    - codelist_from_csv
- Functions
    - case
    - maximum_of
    - minimum_of
- Measures

In the above, Dataset and create_dataset move from General to Dataset; codelist_from_csv moves from General to Codelists; and General is renamed Functions.

**Comment by evansd** [comment]
Thanks, that seems reasonable to me.
