### ISSUE TITLE
Draw the owl

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1633]
As @inglesp has pointed out, the ehrQL tutorial is similar to _How to draw an owl_.

![How to draw an owl](https://github.com/opensafely-core/ehrql/assets/477263/c8409908-812f-493d-9314-3d7ba629d239)

Upon conclusion of the ehrQL tutorial, the reader has created a repo, created (and deleted) a codespace, interacted with the sandbox, created a minimal dataset definition, and generated a dummy dataset that is displayed in the terminal (i.e. it is not written to a file).

To become a competent user of ehrQL, however, the reader should also:

- Expand the dataset definition
- Write a dummy dataset to a file
- Commit the dataset definition to `main`

## Expand the dataset definition

I'd like to check with a couple of researchers about what "expand" most usefully means,[^2] but based on [this dataset definition][1], which @alschaffer said was written by her pilots without her help,[^1] I think "expand" probably means:

- Combining Boolean series to define the population (e.g. was born on or before a date and is alive and is either male or female; was registered with a practice on a date; was registered with a practice for a minimum of `k` days)
- Adding some simple demographic variables, such as age and sex
- Adding a complex demographic variable, such as ethnicity (`codelist_from_csv`)
- Adding a complex socioeconomic variable, such as IMD quintile (`case`)
- Deriving a variable, such as counting the number of medications within the last 30 days (`.is_in`, `.is_on_or_between`, `days`, `.count_for_patient`)

## Write a dummy dataset to a file

The reader should add an associated action to *project.yaml*, which they will run with `opensafely run [action]`. They should compare and contrast `run` with `exec`, noticing that `exec` is good for eyeballing the data but `run` is good for developing downstream actions, especially when the dummy dataset isn't written to a CSV file.

## Commit the dataset definition to `main`

Upon conclusion of the ehrQL tutorial, the reader will be at "Initial commit" and be ready to run the associated action on OpenSAFELY Jobs. (Crating a project and workspace, and using OpenSAFELY Jobs is out of scope.) Also, they will have created an artefact inside the codespace that persists outside the codespace.

The reader shouldn't commit the dataset definition to a feature branch and open a pull request, because different projects and different organizations have different guidelines about feature branches and pull requests.

[1]: https://github.com/opensafely/end-of-life-carequality/blob/main/analysis/ehrql/dataset_definition_ehrql_example.py

[^1]: https://bennettoxford.slack.com/archives/C31D62X5X/p1695306487454799
[^2]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1696001906535959

**Comment by iaindillingham** [comment]
I'm putting together an extended dataset definition [in this gist](https://gist.github.com/iaindillingham/5e5f5eaaaf0eb8d9bfd8f7ce15787deb), with feedback in Slack.[^1]

[^1]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1696001906535959

**Comment by iaindillingham** [comment]
Thanks, @sebbacon. At the moment, the expanded dataset definition hits several of those. I don't think it can hit them all, but hitting several suggests that it will be useful.

**Comment by sebbacon** [comment]
> I don't think it can hit them all

Devil's advocate: why not? If nearly every study includes all of them anyway:

* It's didactically useful as it covers all common cases
* It's pragmatically useful for the same reason
* It helps extend our "best-practice" reach deeper into peoples' code

**Comment by iaindillingham** [comment]
Because it's a tutorial and not a how-to. Hitting all of them will make the tutorial longer, which means it will take more time to complete and more time to maintain. I think a more effective use of time would be to incorporate several into the tutorial and the remainder into how-tos, or, indeed, reusable variables.

**Comment by sebbacon** [comment]
Fair, I think I'm eliding our _tutorial_ with our _research template_.

It leads me to ask if this part of the _tutorial content_ might also live in the _research template_?

The familiarity when moving on from the tutorial could be helpful.

**Comment by iaindillingham** [comment]
It could, but I think that's a separate issue, so I've created opensafely/research-template#108.
