### ISSUE TITLE
`KeyError` when `.then` is passed `None`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1637]
Until we pick up #1548, missing data in `addresses.imd_rounded` are represented as `-1` rather than `None`. When grouping rounded IMD into quintiles, I could handle missing data like this

```py
imd_rounded = addresses.for_patient_on(index_date).imd_rounded
max_imd = 32844

dataset.imd_quintile = case(
    when((imd_rounded >= 0) & (imd_rounded < int(max_imd * 1 / 5))).then(1),
    when(imd_rounded < int(max_imd * 2 / 5)).then(2),
    when(imd_rounded < int(max_imd * 3 / 5)).then(3),
    when(imd_rounded < int(max_imd * 4 / 5)).then(4),
    when(imd_rounded <= max_imd).then(5),
)
```

but I thought that handling missing data like this was easier to reason about

```py
dataset.imd_quintile = case(
    when(imd_rounded < 0).then(None),
    when(imd_rounded < int(max_imd * 1 / 5)).then(1),
    when(imd_rounded < int(max_imd * 2 / 5)).then(2),
    when(imd_rounded < int(max_imd * 3 / 5)).then(3),
    when(imd_rounded < int(max_imd * 4 / 5)).then(4),
    when(imd_rounded <= max_imd).then(5),
)
```

However, the latter raises

```
Traceback (most recent call last):
  File "/app/ehrql/query_language.py", line 933, in _wrap
    cls = REGISTERED_TYPES[type_, is_patient_level]
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: (<class 'NoneType'>, True)
```

I think there probably are other times when a researcher wants to pass `None` to `.then`, even after we've picked up #1548.

**Comment by evansd** [comment]
This is a simple feature to describe, but it's actually non-trivial to implement as currently the query model doesn't support introducing explicit nulls.

We could start by making the right hand side of the `Case.cases` dict nullable. But it may require more futzing around with the type system to get everything working properly.

**Comment by iaindillingham** [comment]
It sounds like we should keep this issue open, but not work on it until we've encountered other times when we want to call `.then(None)`.

**Comment by evansd** [comment]
Adding a few notes off the top of my head before discussion. Things that would need changing are:

The type signature here:
https://github.com/opensafely-core/ehrql/blob/f7f8e398264866c7314e6484e0e8adc52b021897/ehrql/query_model/nodes.py#L428-L430
would need to change to something like:
```py
 class Case(Series[T]): 
     cases: Mapping[Series[bool], Series[T] | None] 
     default: Series[T] | None = None 
```

We'd need to teach `get_domain` to treat `NoneType` as having `Domain.PATIENT`:
https://github.com/opensafely-core/ehrql/blob/f7f8e398264866c7314e6484e0e8adc52b021897/ehrql/query_model/nodes.py#L604-L613

We'd need to teach `get_typespec_for_mapping` to handle heterogeneous types involving `None`:
https://github.com/opensafely-core/ehrql/blob/f7f8e398264866c7314e6484e0e8adc52b021897/ehrql/utils/typing_utils.py#L161-L178

That is, if you have a dict like `{0: "a", 1: "b", 2: None}` then its typespec should be:
```
dict[int, str | None]
```

We'd then need to make sure the type-matching code can handle union types like `str | None` correctly:
https://github.com/opensafely-core/ehrql/blob/f7f8e398264866c7314e6484e0e8adc52b021897/ehrql/utils/typing_utils.py#L20

Possibly the type-checking stuff will just work after all that, but there may be things I've missed.

I'd suggest adding a new `None` case to the example in the unit tests and then getting that passing:
https://github.com/opensafely-core/ehrql/blob/f7f8e398264866c7314e6484e0e8adc52b021897/tests/unit/query_model/test_nodes.py#L59-L66

Hopefully that's the hard part and the query language and query engine changes will be comparatively straightforward.
