### ISSUE TITLE
Move raw tables into separate module

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1665]
We have ehrQL tables that transform their corresponding database tables to some degree.[^2] Examples include `patients`, `ons_deaths`, and `wl_clockstops`. We also have raw ehrQL tables that give more-or-less direct access to the database tables. At present, `isaric_raw`, `wl_clockstops_raw`, and `wl_openpathways_raw` are the only raw tables.

Tables and raw tables live side-by-side in the same modules, which in practice means side-by-side in `ehrql.tables.beta.tpp`. To distinguish between tables and raw tables, raw tables have the prefix `raw_`. However, as @sebbacon pointed out,[^1] this gives raw tables the same status as tables. This is undesirable: we'd prefer researchers to use tables rather than raw tables. To encourage researchers, we should lower the status of raw tables.

Moving raw tables to `ehrql.tables.beta.raw.tpp` would lower the status of raw tables. It would also give a clear location in [the table schemas documentation][1] for describing them. As only [opensafely/isaric-exploration][] references a raw table, we can move the raw tables without a deprecation period, as long as we open a PR on the study so as not to confuse Millie and Will.

To make this issue more tractable, I've chosen to avoid the question of what "beta" means. And of what makes a table a table, rather than a raw table. (Some tables don't involve transforming the database tables; some raw tables do.) And of whether "raw" is the right adjective.

[^1]: https://bennettoxford.slack.com/archives/C03FB777L1M/p1697533816749729
[^2]: @inglesp has called these "cooked" ehrQL tables 👨🏻‍🍳 

[1]: https://docs.opensafely.org/ehrql/reference/schemas/
[opensafely/isaric-exploration]: https://github.com/opensafely/isaric-exploration

**Comment by evansd** [comment]
I know you're deliberately avoiding the "beta" question, but for what it's worth I think it would be reasonable to stick these directly under `ehrql.tables.raw`.

The reason for the `beta` namespace was to make me personally more relaxed about shoving things in there to unblock us without having to worry too much about the important and difficult question of how best to present data to our users.

I don't think the raw tables suffer from the same considerations as there's relatively little decision making that goes in to their presentation.

**Comment by inglesp** [comment]
This looks like a sensible approach.

I originally also thought we could put them in `ehrql.tables.raw`.  But given that they may change, and so we may want to version them, putting them under a `beta` namespace gives us more wiggle room later.

**Comment by iaindillingham** [comment]
Thanks for your comments, both.
