### ISSUE TITLE
Docs for `generate-meaures --dummy-data-file` are confusing

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1690]
The docs are here:
https://docs.opensafely.org/ehrql/reference/cli/#generate-measures.dummy-data-file

This is because both `generate-dataset` and `generate-measures` use the same function to define the `dummy-data-file` argument:
https://github.com/opensafely-core/ehrql/blob/e61333d7fd09000dd91e5c97a94270e7abd32b71/ehrql/__main__.py#L386-L405

The simplest solution would be to inline the function and customise the help text for each context.

**Comment by inglesp** [comment]
Closing in favour of #975.
