### ISSUE TITLE
Query processor unable to produce a query plan

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1702]
Two jobs in [this job request][1] failed; MSSQL reported that the query processor was unable to produce a query plan. @liang-yu12 thinks the failures relate to a large codelist.[^1]

[1]: https://jobs.opensafely.org/the-healthcare-utilisation-of-people-with-long-covid-openprompt/healthcare_utilisation_openprompt/20978/

[^1]: https://bennettoxford.slack.com/archives/C010SJ89SA3/p1699269501128539

**Comment by inglesp** [comment]
We've made a suggestion on the thread.

For a longer term fix, see #512.
