### ISSUE TITLE
Add a constraint for addresses.rural_urban_classification

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/ehrql#1734]
rural_urban_classification only takes an integer 1-8 (and -1), but ehrql currently allows any integer, which results in some unexpected dummy data being generated.

Old docs for cohort-extract [document the values](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.address_as_of)

-1 presumably means missing/unknown (the column is non-nullable)

**Comment by inglesp** [comment]
This is covered in #800.
