### ISSUE TITLE
Remove `hospital_admissions.primary_diagnoses`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/ehrql#1758]
`hospital_admissions.primary_diagnoses` (plural) is deprecated, in favour of `hospital_admissions.primary_diagnosis` (singular). As [the description][1] says, this is because the underlying column contains a single diagnosis code.

We should remove `hospital_admissions.primary_diagnoses`. Most occurrences seem to be study definitions, so it shouldn't be too much of a headache to open PRs on the small number of repos that contain dataset definitions.

[1]: https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/#hospital_admissions.primary_diagnoses

**Comment by inglesp** [comment]
Thanks -- already covered by a note in #934.
