### ISSUE TITLE
Restrict access to appointments data

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/ehrql#1970]
The [appointments](https://docs.opensafely.org/ehrql/reference/schemas/tpp/#appointments) table is something of a "use with caution" dataset; there are lots of ways to misuse it, some of which could lead to unsafe conclusions.

We have decided we need to do a bit more curation and reporting work on it before it can be widely used.

Until then, we should restrict access on a per-project basis, using [the mechanism we have in place for things like ICNARC](https://github.com/opensafely-core/opensafely-cli/blob/main/repository_permissions.yaml).

Implementing this change will require

* Doing the wiring
* Double-checking if there are ongoing projects that need access
* Coming up with some wording for the documentation

For the latter two, liaise directly with @brianmackenna

**Comment by Jongmassey** [comment]
As well as updating `repository_permissions.yaml`,  we'll also need to update `check.py` with the right ehrql/cohortextractor signatures for the dataset:

https://github.com/opensafely-core/opensafely-cli/blob/main/opensafely/check.py#L24-L68

**Comment by rebkwok** [comment]
Additional study repos using appointments table:
https://github.com/opensafely/end-of-life-carequality

**Comment by brianmackenna** [comment]
> Double-checking if there are ongoing projects that need access
Nuffield Trust one which I think is covered by https://github.com/opensafely/end-of-life-carequality that @rebkwok has found. I'll check if they have other repos

There are some other groups who looked at appointment type stuff - what is the easiest way to get the full list of people/projects who used `https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_gp_consultations` so I can have a look to see who might need to have access in the future?



> Coming up with some wording for the documentation

1. @alexwalkerepi or others on the winter pressures stuff - can you prepare a draft please from the work already done please?
1. others to input as appropriate
1. Me @amirmehrkar to "approve" final wording

**Comment by Jongmassey** [comment]
I've had quite a few automated emails about this: [cox-ipw](https://github.com/opensafely-actions/cox-ipw/issues/49) and [shielding-evaluation](https://github.com/opensafely/shielding-evaluation/issues/95) most recently

**Comment by Jongmassey** [comment]
also [digital-access-to-primary-care](https://github.com/opensafely/digital-access-to-primary-care/issues/69)

**Comment by Jongmassey** [comment]
and [post-covid-autoimmune](https://github.com/opensafely/post-covid-autoimmune/issues/61)

**Comment by Jongmassey** [comment]
[post-covid-renal](https://github.com/opensafely/post-covid-renal/issues/30) too

**Comment by rebkwok** [comment]
With some better searching (still in the main branch only), these are all the repos that use the appointments dataset (either the ehrql `appointments` table, or cohort-extractor's `with_gp_consultations`):

[DISECT_UK_India_COVID](https://github.com/opensafely/DISECT_UK_India_COVID)
[OS_OC_v001-research](https://github.com/opensafely/OS_OC_v001-research)
[OS_VidGroupClinic_v001-research](https://github.com/opensafely/OS_VidGroupClinic_v001-research)
[Pancreatic_cancer](https://github.com/opensafely/Pancreatic_cancer)
[Post_covid_nice_compliance](https://github.com/opensafely/Post_covid_nice_compliance)
[SRO-PULSE-OXIMETRY-UPD](https://github.com/opensafely/SRO-PULSE-OXIMETRY-UPD)
[ace-arb-research](https://github.com/opensafely/ace-arb-research)
[amr-uom-brit](https://github.com/opensafely/amr-uom-brit)
[anticoagulants-research](https://github.com/opensafely/anticoagulants-research)
[avoidable_hospitalisations_trends](https://github.com/opensafely/avoidable_hospitalisations_trends)
[ckd-healthcare-use](https://github.com/opensafely/ckd-healthcare-use)
[covid-aki-outcomes](https://github.com/opensafely/covid-aki-outcomes)
[covid-unvaccinated-aimpaper](https://github.com/opensafely/covid-unvaccinated-aimpaper)
[deaths-at-home-covid19](https://github.com/opensafely/deaths-at-home-covid19)
[digital-access-to-primary-care](https://github.com/opensafely/digital-access-to-primary-care)
[early-inflammatory-arthritis](https://github.com/opensafely/early-inflammatory-arthritis)
[end-of-life-carequality](https://github.com/opensafely/end-of-life-carequality)
[feather-to-dta](https://github.com/opensafely/feather-to-dta)
[flu-vacc-research](https://github.com/opensafely/flu-vacc-research)
[hdruk-os-covid-paeds](https://github.com/opensafely/hdruk-os-covid-paeds)
[hydroxychloroquine-research](https://github.com/opensafely/hydroxychloroquine-research)
[immunosuppressant-meds-research](https://github.com/opensafely/immunosuppressant-meds-research)
[lockdown-and-vulnerable-groups](https://github.com/opensafely/lockdown-and-vulnerable-groups)
[long-covid-risk-factors-and-prediction](https://github.com/opensafely/long-covid-risk-factors-and-prediction)
[long-covid-symptoms](https://github.com/opensafely/long-covid-symptoms)
[nsaids-covid-research](https://github.com/opensafely/nsaids-covid-research)
[nsaids-research-archive](https://github.com/opensafely/nsaids-research-archive)
[openprompt_health_utilisation](https://github.com/opensafely/openprompt_health_utilisation)
[oral-anticoagulant-covid](https://github.com/opensafely/oral-anticoagulant-covid)
[post-covid-autoimmune](https://github.com/opensafely/post-covid-autoimmune)
[post-covid-bristol](https://github.com/opensafely/post-covid-bristol)
[post-covid-cvd-methods](https://github.com/opensafely/post-covid-cvd-methods)
[post-covid-cvd-methods-redux](https://github.com/opensafely/post-covid-cvd-methods-redux)
[post-covid-diabetes](https://github.com/opensafely/post-covid-diabetes)
[post-covid-gastrointestinal](https://github.com/opensafely/post-covid-gastrointestinal)
[post-covid-kidney-outcomes](https://github.com/opensafely/post-covid-kidney-outcomes)
[post-covid-mentalhealth](https://github.com/opensafely/post-covid-mentalhealth)
[post-covid-neurodegenerative](https://github.com/opensafely/post-covid-neurodegenerative)
[post-covid-pre-vaccinated-cardiovascular](https://github.com/opensafely/post-covid-pre-vaccinated-cardiovascular)
[post-covid-renal](https://github.com/opensafely/post-covid-renal)
[post-covid-respiratory](https://github.com/opensafely/post-covid-respiratory)
[post-covid-respiratory-incident-events](https://github.com/opensafely/post-covid-respiratory-incident-events)
[post-covid-unvaccinated](https://github.com/opensafely/post-covid-unvaccinated)
[post-covid-vaccinated](https://github.com/opensafely/post-covid-vaccinated)
[principle-inhaler-uptake](https://github.com/opensafely/principle-inhaler-uptake)
[risk-factors-research](https://github.com/opensafely/risk-factors-research)
[suicide-deaths-pcc](https://github.com/opensafely/suicide-deaths-pcc)
[uom_pregnancy_tx_pathways](https://github.com/opensafely/uom_pregnancy_tx_pathways)
[winter-pressures](https://github.com/opensafely/winter-pressures)

**Comment by rebkwok** [comment]
@brianmackenna full list of repos ☝

**Comment by iaindillingham** [comment]
Just to say that I'm speaking to Juliet about the notifications the IG team receive when repos query the `Appointment` table, but these repos haven't been granted access. I'm concerned that these notifications are confusing.

Now that the PR has been merged into `opensafely` (opensafely-core/opensafely-cli#247), is the plan to add the above repos to `RESTRICTED_DATASETS`?

**Comment by rebkwok** [comment]
@alexwalkerepi is handling new requests to use the data
Docs added here https://github.com/opensafely-core/ehrql/pull/1990
