### ISSUE TITLE
Define criteria for tables/columns to be provided in `example-table` CSV files

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2146]
- See [Slack conversion](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1728308865306139) and [this comment](https://github.com/opensafely-core/ehrql/pull/2143#discussion_r1791471961) in #2143.
- Currently it is unclear what tables should be included as CSV files in the example data. @evansd suggested that all core tables + all tables used in the tutorial would make sense
  - If so, we should add a CSV file representing the `tpp.apcs` table
- Once the criteria is set, the [test file](https://github.com/opensafely-core/ehrql/blob/main/tests/unit/test_example_data.py) for example data should be updated to remove the hard-coding of tables. 
- We should also look at whether our example CSV files ought to include all the columns of the tables they represent
  - If so, add the columns and use `allow_missing_columns=False` in the tests

**Comment by evansd** [comment]
We've decided to take the approach of:
1. expanding the core tables to include `practice_registrations`;
2. rewriting the more complex tutorial definition to only use core tables.

This allows us to make the policy very simple:
 * The tutorial examples should only use core tables.
 * We should provide example data for all core tables.
