### ISSUE TITLE
Are there any UX improvements that could be made to the sandbox?

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2162]
We know that some users have made extensive use of the sandbox while learning ehrQL.  At the moment, it's a very thin wrapper around Python's `code.interact()`.

We should talk to users to find out whether there are any usability improvements we could make.  (When we ask them, it's possible they'll make suggestions related to ehrQL itself.  These will be worth capturing!  But work on this ticket should focus on the sandbox.)

**Comment by alarthast** [comment]
User interview write-ups in [this Google Doc](https://docs.google.com/document/d/1PeMw-oo6xmEZgeyeDwY7YVE8u8IiCvhfnSzdrGU0hGo/edit?tab=t.0)

**Comment by alarthast** [comment]
A common theme from the interviews is that users often "learn ehrQL by doing", i.e. they start to write dataset definitions / measures for the actual study they want to do after finishing the tutorial. 
The sandbox soon becomes insufficient for their needs as they would write dataset definitions that import self-created modules, codelist files etc., and it's hard to copy and paste all that pretext into the sandbox before they can input the small chunk of code they'd like to test into the sandbox.

Potential improvements we could make:
- [ ] Simplify the process for starting the sandbox
  - [ ] Pre-dump example-data in `research-template` and put it in the `.gitignore`
  - [ ] Default to using example-data if no filepath provided
- [ ] Simplify the process to customise the example data that the sandbox uses (Overlaps with #2178 and its future successors)
- [ ] Make it possible to start the sandbox at the middle of a file, i.e. `ehrql sandbox (example-data) --file analysis/dataset_definition.py --line 42`
- [ ] Or, as an alternative to the above item,
  - [ ] Set the sandbox PYTHONPATH such that user-defined modules can be detected (Might require the path to these module to be interactively definable)
  - [ ] Similarly configure for straightforward usage of `codelist_from_csv`

Ideas that might take more work:
- [ ] Make it possible to run a [Jupyter notebook](https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8) using the sandbox engine? Would solve issues concerning the terminal being difficult to navigate (e.g. cannot point-and-click to edit, copy and pasting). Depends on how many issues would already be solved by #2167.

**Comment by inglesp** [comment]
The VS Code extension is the improvement to the sandbox.
