### ISSUE TITLE
Are there any UX improvements that could be made to writing ehrQL in VSCode?

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2163]
We encourage users to write code in VSCode.  There are probably things we could do to provide a more helpful experience, including:

* shortcuts to generate a dummy dataset from within the editor
* improving autocomplete
* improving the squiggly line error messages

We should also ask users whether they think there are any UX features they miss from other editors/IDEs such as RStudio.

Having come up with a list of possible improvements, we should spend a short amount of time trying to understand how much effort it would take to implement and maintain the new features.

This ticket does not include any implementation work.

**Comment by rebkwok** [comment]
Closing in favour of new autocomplete tickets:
https://github.com/opensafely-core/research-template-docker/issues/84
https://github.com/opensafely-core/opensafely-vscode/issues/14
https://github.com/opensafely-core/ehrql/issues/2308
