### ISSUE TITLE
What common queries appear across many dataset definitions?

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2164]
It has always been a goal that ehrQL's composability should allow us to provide reusable variables for researchers to use out of the box.  We already provide some, including [`patients.age_on`](https://docs.opensafely.org/ehrql/reference/schemas/tpp/#patients.age_on) and [`practice_registrations.spanning`](https://docs.opensafely.org/ehrql/reference/schemas/tpp/#practice_registrations.spanning).

We should review existing ehrQL code (via [this search](https://github.com/search?type=code&q=org%3Aopensafely+language%3Ayaml+ehrql) should find all projects using ehrQL) and look for common patterns that we could add to the ehrQL package.  These could either be more methods on tables (like `patients.age_on`) or more complicated queries, such as BMI or ethnicity, which do not necessarily live on a table.

This ticket does not include any implementation work.

**Comment by eli-miriam** [comment]
I've got a doc [here](https://docs.google.com/document/d/1rEdlkNJ57DWuq8bv8KDcDs4hWdCHe6V0xJ5yTGNzzOU/edit#heading=h.u0rd76j4r74) with everything I've pulled together. When condensed down, it doesn't look like a lot, but this was a _really_ helpful exercise for me in terms of understanding the ehrQL part of researchers' output.

**Comment by rw251** [comment]
And now [here](https://docs.google.com/document/d/1wX8ZD8G4-jxAT7-gfpxkfoNwEAWf-IGou4KJdWCLLVI/) is my review doc. I think it complements Eli's doc pretty well as Eli has pulled out the common code snippets, while I've focussed on the general patterns.

**Comment by inglesp** [comment]
Thanks both.  Time to move onto implementation in #2201.
