### ISSUE TITLE
Make a cheat sheet

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2170]
In his suggestions for improving the ehrQL docs (https://github.com/opensafely/documentation/issues/1592), @JaidipGill suggested a cheat sheet:

> An ehrQL [cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) could provide users a quick view of the most common syntax rather than having to read long, text-heavy tutorials/references.

ehrQL is much simpler than Pandas, so an ehrQL cheat sheet should be much simpler than the Pandas cheat sheet that Jaidip linked to.

I'm not sure exactly what form this should take.  Whoever takes this one should produce one or more scrappy drafts for early feedback before investing significant effort.

**Comment by inglesp** [comment]
Tom's going to draft a first version.

**Comment by madwort** [comment]
with colours

![Image](https://github.com/user-attachments/assets/5be53f64-57ff-4d16-af23-b9ac01eef38e)
![Image](https://github.com/user-attachments/assets/917de2cf-0abf-4a88-825f-c5a623511148)

**Comment by madwort** [comment]
https://github.com/opensafely-core/ehrql/pull/2239
