### ISSUE TITLE
All cause mortality outcome is empty with 0 events

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/ehrql#2253]
The following is an issue found by Em Prestige from LSHTM ([Slack source thread](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1732698008391349)).

---

I have an outcome for all cause mortality which is using the ONS death date (extracted as follows: `dataset.death_date = ONS_deaths.date`) and is then processed as follows:

```python
df_input <- df_input %>%
  mutate(
    #infer presence of all cause mortality
    all_cause_mortality_date = if_else(death_date <= patient_end_date, death_date, NA_Date_),
    all_cause_mortality = if_else(
      !is.na(all_cause_mortality_date), TRUE, FALSE)
  )

.
.
. 

  df_input <- df_input %>%
    mutate(
      #infer all cause mortality outcome
      all_cause_mortality_inf_date = case_when(
        is.na(all_cause_mortality_date) & is.na(deregistration_date) & is.na(death_date) ~ patient_end_date,
        is.na(all_cause_mortality_date) & is.na(deregistration_date) & !is.na(death_date) ~ 
          if_else(death_date <= patient_end_date, death_date, patient_end_date),
        is.na(all_cause_mortality_date) & !is.na(deregistration_date) ~ deregistration_date,
        TRUE ~ all_cause_mortality_date),
      #assign censoring indicator
      all_cause_mortality_censor = if_else(is.na(all_cause_mortality_date), 1, 0),
      #infer all cause mortality outcome
      all_cause_mortality_inf = if_else(all_cause_mortality_censor == 0, 1, 0)
    )
```

where `patient_end_date` is a patient specific end to follow up (the earliest date of either the end of the study period or the patient "aging-out" of the cohort).

Other mortality outcomes are handled somewhat similarly and have no issues - however, the all cause mortality outcome is completely empty, 0 events. I've checked the pipeline against both my own provided dummy data, and the ehrQL generated dummy data and both don't seem to replicate this strange output.

**Comment by evansd** [comment]
I don't think we're 100% clear on what the issue is here, but I think we've established that it's not an ehrQL problem. Will is helping with the R side of things.
