### ISSUE TITLE
Consider explaining the difference between a table and a dataset

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2280]
The old tutorial had a section about how a table and a dataset are different.

https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/working-with-tables/index.md?plain=1#L139-L143

In the current tutorial, we say something like this, which is similar (but says that a dataset is a table of patients). Do we need to add / clarify anything?

https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/tutorial/working-with-data-with-ehrql/index.md?plain=1#L1-L3

**Comment by inglesp** [comment]
I don't think that this is necessary.  I prefer the new version, where the definition is a bit more explicit.
