### ISSUE TITLE
Consider adding a screenshot of the terminal

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2282]
In the old tutorial, we explained what a terminal is
https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/setting-up/index.md?plain=1#L48-L63

and showed a screenshot of the terminal
https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/setting-up/index.md?plain=1#L73
![Image](https://github.com/user-attachments/assets/c6484d67-9004-4594-bba6-1276eb1945d7)

We currently simplified this to 
https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/tutorial/using-ehrql-as-part-of-a-study/index.md?plain=1#L7-L13

which should be enough, but a screenshot would not hurt.

**Comment by inglesp** [comment]
Agree, will add.
