### ISSUE TITLE
Consider demonstrating in the tutorial that we can add columns to a dataset that aren't booleans

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2284]
The old tutorial has lines assigning dates and codes to dataset columns (and these lines are still available on the ehrQL homepage):

https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/index.md?plain=1#L73-L74

The current tutorial has only boolean columns in the dataset we build

https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/tutorial/building-a-dataset/index.md?plain=1#L144-L148

This is not a big issue since there are relevant sections in the examples in the how-to guide, but it's worth making sure that we're okay with skipping teaching this in the new tutorial.

**Comment by inglesp** [comment]
Good observation.  Not required for the tutorial (especially as it'd require restructuring the tutorial to deal with different QOF rules).  But we could consider adding something here in future if people get confused.
