### ISSUE TITLE
Confirm we are happy with changing the linked reading for codelists

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2287]
In the old tutorial, the further reading on codelists we used to link to are the bennett blog post and the OS docs

https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/writing-a-more-complex-dataset-definition/index.md?plain=1#L236-L242

We now link to the ehrQL docs:
https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/tutorial/more-complex-transformations/index.md?plain=1#L135
https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/tutorial/more-complex-transformations/index.md?plain=1#L306

which does not link to the above two things. Is this okay?

**Comment by inglesp** [comment]
Let's add a link to the blog post to the main codelist docs.
