### ISSUE TITLE
Do we need to explain what a python dictionary is?

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2288]
In the old tutorial, we had a tip like this:
https://github.com/opensafely-core/ehrql/blob/8896d4fcb3a317c6d2f3cb64f40b28a863850f4c/docs/tutorial/writing-a-more-complex-dataset-definition/index.md?plain=1#L304-L310

We don't have an equivalent in the new tutorial, and python dictionaries are assumed knowledge:
https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/how-to/examples.md?plain=1#L55

I assume the user can find out about dictionaries fairly easily from Googling though.

**Comment by inglesp** [comment]
Yes -- (a) this is not a Python tutorial and (b) we don't use a codelist with categories in the tutorial.
