### ISSUE TITLE
show() should only take ehrQL objects as arguments

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#2295]
We now (since #2275) allow users to use `print()` to print debug statements in their ehrQL dataset definitions.  We should change the behaviour of `show()` so that it raises a suitable error if a user calls it with anything other than either:

1. a single ehrQL object (a dataset, frame, or series), or
2. multiple series drawn from the same domain.

**Comment by rw251** [comment]
Fixed by #2319
