### ISSUE TITLE
Update the explanation docs about the existing sandbox

### ISSUE THREAD

**Issue by alarthast** [opensafely-core/ehrql#2310]
The current section of the explanation docs on the ehrQL sandbox reads:

https://github.com/opensafely-core/ehrql/blob/42b273b92a2bb44078bcfbf7953a9aa5b4917dcd/docs/explanation/running-ehrql.md?plain=1#L30-L33

- Some users won't have used a `learning-ehrql` directory. 
- At the time of writing, new users won't have an `example-data` folder in their tutorial repo (they'd have `dummy_tables` instead).
- Since we do not reference the sandbox in the tutorial anymore, this place might be the first time a user is hearing of the sandbox functionality
- It might be good to point to the docs for the VS Code extension here, given that it offers a similar functionality

It would be good to update this section to address the above bullet points.
At the same time, we should update all the other references to the `learning-ehrql` directory in other sections of the same page.

**Comment by inglesp** [comment]
Made redundant by #2327.
