### ISSUE TITLE
Support `minimum_of`/`maximum_of`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#517]
We want a pair of new functions for finding the minimum and maximum across an arbitrary number of numeric series, ignoring any NULL values.

## Spec test

A basic spec test would look something like:
```py
from ..tables import p

from ehrql import minimum_of, maximum_of


table_data = {
    p: """
          | i1 | i2
        --+----+----
        1 | 10 | 20
        2 | 30 |
        3 |    |
    """,
}


def test_maximum_of_two_integers(spec_test):
    spec_test(
        table_data,
        maximum_of(p.i1, p.i2),
        {
            1: 20,
            2: 30,
            3: None,
        },
    )


def test_minimum_of_two_integers(spec_test):
    spec_test(
        table_data,
        minimum_of(p.i1, p.i2),
        {
            1: 10,
            2: 30,
            3: None,
        },
    )
```

## Query model

The query model operations would be something like:
```py
class Function:
    ...
    class Minimum(Series[Comparable]):
        sources: tuple[Series[Comparable]]

    class Maximum(Series[Comparable]):
        sources: tuple[Series[Comparable]]
```

For the generative tests we'll need to get Hypothesis to pick a number of arguments to supply between 2 and, say, 5 and then generate that number of series as inputs.

## Type casting

We should also make sure our automatic type casting is applied so that it's possible to write things like:
```py
dataset.some_date = minimum_of(some_date_series, "2020-04-01")
```
This will involve finding the first argument which is an instance of `BaseSeries` and then passing all the arguments through its `_cast` method.

## Bikeshedding

These are things we can decide (or change) later on if we need to do and shouldn't block the initial development work.

We've got a few options as to what to call these functions. The only ones definitely off-limits are `min/max` as they're Python built-ins. We could use `minimum/maximum` – I can't decide if the `_of` suffix helps things read more naturally, or it it's just useless noise. The SQL standard uses `greatest/least` to distinguish the functions from the `MIN/MAX` aggregations, but I'm not wild about those.

Another options is that we could make these operations methods on series of `Comparable` type, rather than a pair of new functions. So you could write something like:
```py
dataset.some_date = some_date_series.minimum_of("2020-04-01")
```

This has some advantages:
 * there's not a new thing to import
 * it will show up as an auto-complete option
 * the automatic type casting implementation will be easier

But it also has some disadvantages:
 * the resulting ehrQL doesn't really make sense as English any more, we'd need a different name from `mimimum_of` and I can't think what that is
 * in many cases it's going to be arbitrary which series you use as the object and which as the argument, and that feels like a potential source of confusion

I don't know what the right answer is here. But again, it's not hard to change later if we want to. 

 
## Implementation notes

The cohortextractor implementation is here:
https://github.com/opensafely-core/cohort-extractor/blob/90f27bedede0f2780ff5ec0bc052a0a6dafe8f2d/cohortextractor/patients.py#L2111-L2167

Implementing this for pairs of inputs would be fairly easy using a case statement. Extending that to arbitrarily many inputs would be possible by nesting up the pair comparisons but it all gets pretty convoluted and we can hit database nesting limits.

In some databases we can use the `GREATEST` and `LEAST` functions.

In MSSQL we need to use this Table Value Constructor trick:
https://stackoverflow.com/a/6871572

**Comment by Jongmassey** [comment]
These two seem to be relatively often used in cohort extractor ( [`minimum_of`](https://github.com/search?q=org%3Aopensafely+minimum_of&type=code) [`maximum_of`](https://github.com/search?q=org%3Aopensafely+maximum_of&type=code) ), particularly for finding out the last/first date between different types of event, or sources of the same type of event. I've certainly seen it used to get the earliest recorded date of death across the multiple sources available. 

On this basis, I think we shouldn't wait until one of our five ehrQL2 studies wants to use it and should pre-emptively implement as not to hold up researchers in the quite likely instance that they want it

**Comment by Jongmassey** [comment]
re: bikeshedding - having it as a method on a Series doesn't really make sense to me. `x.maximum_of(y,z)` just doesn't intuitively seem as good as `maximum_of(x,y,z)`. I think this is why in my sketch I made it a class method of EventSeries

**Comment by evansd** [comment]
Yeah, I think I agree. Was just trying to consider the possibile options.
