### ISSUE TITLE
Add `count_distinct` series aggregation

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#546]
This method would go on the `EventSeries` type so as to be available to series of all types:
https://github.com/opensafely-core/databuilder/blob/2ce31449d6e35b21d45a0e96c746c410be6b7ac9/databuilder/query_language.py#L87-L94

There's no support anywhere for it at the moment, so a new query model operation would need to be added, and then support for it added to the query engines.

Creating appropriate spec tests for these methods should drive out all the work that needs doing.

I have a particular use case in mind for the combination of `count_distinct` and [`to_first_of_month`](https://github.com/opensafely-core/databuilder/issues/545) because it will allow us to count the number of distinct months in which a patient was prescribed a medication. This seems to be used as the basis for several variable definitions and we currently have to deal with this in a clunky way by defining a bunch of intermediate binary variables (one for each month) and then using logical expressions to count them.

**Comment by benbc** [comment]
@evansd I think `count_non_null` can be implemented already as `.take(it.is_not_null()).count_for_patient()`. Is there a good reason for adding it as a single operation?

**Comment by benbc** [comment]
See #192 for a specific use case of `count_distinct`.

**Comment by evansd** [comment]
> I think `count_non_null` can be implemented already as `.take(it.is_not_null()).count_for_patient()`

Oh you're quite right, I'm not sure why that didn't occur to me at the time. I think it's because it feels like a question being asked about the series, rather than frame, so I automatically thought it needed to be a series operation.

I think that in the spirit of keeping the query model as small as possible we definitely _shouldn't_ add an operation for this. But I wonder if we might not want to support writing `some_series.count_non_null()` in ehrQL and have it do the right thing. Let's wait until there's actual demand for that though, rather than doing it speculatively.

**Comment by evansd** [comment]
Another use case for this surfaced in Slack:
https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1678105074517999
