### ISSUE TITLE
Allow configuration to be set by env vars

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/ehrql#547]
Cohortextractor currently has some invocation config that can only be supplied via cli args.

This means jobrunner has to to have some specific knowledge about cohortextrator and mutate the cli args: https://github.com/opensafely-core/job-runner/blob/master/jobrunner/actions.py#L24

It would be much nicer if jobrunner could set such configuration as env vars, and not mutate run args.

Much of this is legacy cohortextractor issues, but I'm keen to make sure databuilder avoids the same issue.

**Comment by bloodearnest** [comment]
This possibly is all left overs from when cohortextractor was used as a cli tool

**Comment by inglesp** [comment]
We allow `DATABASE_URL`, `OPENSAFELY_BACKEND`, and `OPENSAFELY_QUERY_ENGINE` to be set via environment variables.  I can't see any other config that would need to be set via flag munging.
