### ISSUE TITLE
Refactor query model transformation code

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#573]
In order to facilitate efficient execution of queries, or to make parts of the query engine code simpler, we want to be able to rewrite the query model structure given to us by the user in various ways.

We currently do this in fairly [inelegant](https://github.com/opensafely-core/databuilder/blob/116a7f72fc51bf3f8cfa4586b84368735748869f/databuilder/query_model_transforms.py) fashion, by duplicating the entire structure and then updating bits of it in place. This has already led to one [bug](https://github.com/opensafely-core/databuilder/pull/570).

We should take a different approach here, probably using something like a [zipper](https://en.wikipedia.org/wiki/Zipper_(data_structure)) data structure.

This is not urgent, but it will become increasingly important to get this right as we start adding more sorts of transformation.

**Comment by inglesp** [comment]
@evansd can you update the description in light of #1003?

**Comment by evansd** [comment]
I was going to wait until that was merged in case there turned out to be some show-stopping flaw in my approach and we had to resort the nuclear option (a shared cache of hashes which can be globally invalidated).

**Comment by evansd** [comment]
Closing this issue following the work done in:
 * #1003 

I'm not claiming that's the last word in query transformation, but it does mean that this code no longer stands out as a thing which needs refactoring over and above other things we'd like to improve.
