### ISSUE TITLE
Support Stata output format (`dta`/`dta.gz`)

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#794]
Absence of this feature doesn't completely prevent using Stata with Data Builder, but it would mean using the `csv`/`csv.gz` format which we would like to discourage.

There's an open question as to what library we use to implement this. In cohortextractor we used Pandas, but we really want to stream the results to disk as we do for [Arrow files](https://github.com/opensafely-core/databuilder/pull/673).

There's a C library here:
https://github.com/WizardMac/ReadStat

With a Python wrapper here:
https://github.com/Roche/pyreadstat

But the Python library looks Pandas orientated and so may not help us much in any case.

Another possibility is to fork/call into, Pandas's own Stata library so that we can write files without having to build a DataFrame first:
https://github.com/pandas-dev/pandas/blob/v1.5.1/pandas/io/stata.py

Another open question is how we should encode categoricals. In cohortextractor we ended up encoding them (wastefully) as strings because we didn't know the categories upfront and so couldn't index them in a consistent order which caused [problems](https://github.com/opensafely-core/cohort-extractor/issues/534). Given that Data Builder knows the categories [upfront](https://github.com/opensafely-core/databuilder/pull/736) I'm hoping this won't be a problem, but we should check with a Stata-knowledgeable person that this is correct.

See previous discussion in #507 which the ticket replaces.

**Comment by evansd** [comment]
The format is documented here:
https://www.stata.com/help.cgi?dta#definition

And there's a helpful summary here:
https://www.loc.gov/preservation/digital/formats/fdd/fdd000471.shtml

There are various versions of the format but I think we'd want to target v118. That's what the latest version of Stata will output by default, only resorting to v119 if there are more than 32,767 variables. I think Data Builder would fall over for other reasons if we tried to produce a file with that many variables.

The format itself is a strange sort of XML-like syntax with binary blobs mixed in. Writing our own encoder for it would be moderately tedious but perfectly achievable, I think. Particularly since we can use the (BSD licensed) Pandas code for reference/inspiration.

Unfortunately, the `.dta` format is fundamentally streaming-unfriendly as the header block specifies the total number of rows in the file, which we won't know until we've finished streaming. For uncompressed files we can work around this easily enough by updating the header block after the fact. The value is written as a fixed sized binary blob, so as long as we keep track of its offset in the file we can safely overwrite it.

For gzip compressed files things get a bit more tricky. Given that we'll control the compression we ought to be able to write the header out as an uncompressed DEFLATE block, meaning that we can still overwrite the row count value after the fact without affecting downstream data. However the gzip format (which wraps the underlying DEFLATE stream) appends a CRC-32 checksum in a trailer which will no longer match if we mess with the header.

Given the linear nature of CRC I'm _pretty_ sure we can calculate the new checksum without having to read all the data again, but it might be [a bit fiddly](https://stackoverflow.com/questions/23122312/crc-calculation-of-a-mostly-static-data-stream).

**Comment by evansd** [comment]
### Use `dta.zstd`?

It turns out Stata doesn't have native gzip support in any case. The `gzuse` package just creates a temporary file and [shells out](https://github.com/opensafely-core/stata-docker/blob/a8ef637b3e4e7dec068ddbff6673be0ae5c93c8c/libraries/gzuse.ado#L36-L39) to `gzip` :disappointed: 
```do
tempfile tmpdat
shell gzip -dc "`gzfile'" > `tmpdat'

use `initlist' `usind' `tmpdat', clear `options'
```

While this obviously isn't great, it means we're free to use better formats than gzip. We just need to bundle the decompression binary into our Stata image. Zstandard seems like a pretty good choice for generic compression tasks like this. Its format also lends itself to the kind of in-place modification described above: we can write an initial uncompressed frame without any checksum that we can modify, and then compress the rest of the stream as normal.

The [Python bindings](https://python-zstandard.readthedocs.io/en/latest/) provide low enough level access to do this kind of thing.

**Comment by evansd** [comment]
### Teach Stata to read `.arrow` files?

Stata has a [plugin](https://www.stata.com/plugins/) system. And in particular, it supports plugins written in [Python](https://www.stata.com/python/). This gives us two options for teaching Stata to read `.arrow` files.

#### 1. Python plugin

We can write some Python which imports the Stata Function Interface (`sfi`) module and uses `sfi.Data` to populate the current Stata dataset just as loading a data file would:
https://www.stata.com/python/api17/Data.html#sfi.Data.store

There's an example of a similar sort of plugin called [`readit`](https://github.com/wbuchanan/readit/blob/fbd572c30b7bac97d864b2380cefc71a483f5672/readit.ado), although this embeds the Python directly inside the Stata code, which I don't think we'd want to do.

At a high-level we would:
 * read the `.arrow` file headers using PyArrow to gets the column names/types/categories;
 * use the various `addVarXXXX()` methods to create the necessary variables (along with `setVarFormat()` and [`ValueLabel`](https://www.stata.com/python/api17/ValueLabel.html) to format them correctly);
 * read in a batch of records;
 * use `addObs()` to increase the number of "observations" (Stata-speak for rows);
 * use `store()` to write data from the record batch into Stata's dataset;
 * repeat until we're done.

The key question here will be how efficient the `store()` process is. The [`sfi` module](https://github.com/opensafely-core/stata-docker/blob/main/bin/ado/base/py/sfi.py) itself is a thin Python wrapper around a compiled library (`stata_plugin`) whose source we don't have, so I can't really see what it's doing under the hood.

I suspect (due to naming similarities) that it was probably originally based on this plugin, but I don't think we can learn all that much for this:
https://github.com/jrfiedler/python-in-stata/blob/master/core/python_plugin.c


#### 2. Native plugin

If the performance of using a Python plugin isn't acceptable then it's also possible to write compiled plugins. For example, someone has attempted to use the Arrow library to teach Stata to speak Parquet:
https://github.com/mcaceresb/stata-parquet

I've no idea whether, or how well, this works but it doesn't look like it's actively maintained.

**Comment by evansd** [comment]
### Output Stata-flavoured CSV?

Stata only has three basic [data types](https://www.stata.com/manuals/ddatatypes.pdf) with different sized variations:
 * integers (`byte`, `int`, `long`);
 * floats (`float`, `double`);
 * strings (fixed and variable length).

These types are such that Stata can infer the appropriate column type directly from CSV so, in one sense, we don't lose important type information by going via CSV. 

What we do lose though is presentational information: variables can have formatting and per-value labels associated with them which affect how they are displayed in tables and charts.

We could output CSV in a format ready for Stata, signalled by the extension `.stata.csv` (or `.stata.csv.gz`). This would involve:
 * encoding booleans as `0` and `1`;
 * encoding dates as an integer of days since `1960-01-01`;
 * encoding categoricals as integer category indices.

This would mean the data was ready to work with without needing pre-processing, but without the presentational information. But perhaps we could generate the commands needed to apply the presentational information and output these as part of the Data Builder logs (just when generating `.stata.csv`). 

These would look something like:

**Booleans**:
```do
label define boolean 0 "false" 1 "true"
label values BOOL_VAR_NAME boolean
```

**Dates**:
```do
format DATE_VAR_NAME %td
```

**Categoricals**:
```do
label define CAT_VAR_NAME 0 "first_category" 1 "second_category" 2 "third_category" ...
label values CAT_VAR_NAME CAT_VAR_NAME
```

**Comment by Jongmassey** [comment]
re: `stata-parquet` have you read [this](https://www.nber.org/data-formats-census-files)

**Comment by StevenMaude** [comment]
Is this issue essentially redundant with #23 getting merged?

That is, we should tell all users to use `.arrow`?
