### ISSUE TITLE
Expand TPP schema to cover everything available via cohortextractor

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#799]
The current version of the TPP [schema](https://github.com/opensafely-core/databuilder/blob/39bc9fdd2895020b50b341b3a4957f43d55df2f7/databuilder/tables/beta/tpp.py) and [backend](https://github.com/opensafely-core/databuilder/blob/39bc9fdd2895020b50b341b3a4957f43d55df2f7/databuilder/backends/tpp.py) covers only those tables and columns required for the Comparative Booster study to run. We should expand it to cover all tables and columns which can currently be accessed via Cohort Extractor.

This will involve:
 * Reviewing which columns and tables are available via the Cohort Extractor [TPP backend](https://github.com/opensafely-core/cohort-extractor/blob/main/cohortextractor/tpp_backend.py) and not already covered in Data Builder.
 * Deciding how best to represent these and adding them to the schema (including the full set of categories for any categorical columns c.f. #800).
 * Updating the backend to define an appropriate mapping from the user-facing schema to the underlying database tables.

**Comment by iaindillingham** [comment]
Missing columns from the `Therapeutics` table that are used by `patients.with_covid_therapeutics`:

* TreatmentStartDate
* Received
* Intervention
* CurrentStatus
* COVID_Indication
* Region
* MOL1_high_risk_cohort
* SOT02_risk_cohorts
* CASIM05_risk_cohort
* AgeAtReceivedDate
* FormName
* MOL1_onset_of_symptoms
* SOT02_onset_of_symptoms
* Count
* Der_LoadDate

**Comment by inglesp** [comment]
We've decided that not going to expose data unless we've been asked for it.
