### ISSUE TITLE
Data builder CLI syntax wrong in quick start

### ISSUE THREAD

**Issue by benbc** [opensafely-core/ehrql#815]
The `project.yaml` fragment on [the quick start page](https://docs.opensafely.org/data-builder-quick-start/) in the docs uses the old CLI syntax:

```
      databuilder:v0 generate_dataset
        --dataset-definition analysis/dataset_definition.py
        --dummy-data-file dummy_data.csv
        --output output/dataset.csv
```

**Comment by StevenMaude** [comment]
Closing this following the rewrite in https://github.com/opensafely-core/ehrql/pull/1317 as the associated content has been removed.
