### ISSUE TITLE
Design and implement measures API

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#816]
We need some equivalent to Cohort Extractor's [measures framework](https://docs.opensafely.org/measures/) in Data Builder. It's OK if the first version of this uses the same inefficient implementation as Cohort Extractor. But the API needs to be such it doesn't preclude us swapping this out for a more [efficient implementation](https://github.com/opensafely-core/databuilder/issues/42) further down the road.

**Comment by inglesp** [comment]
A consideration: if we can't ensure that the numerator is a subset of the denominator, then we should at least document it clearly.  See [this Slack thread](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1664978145256269).

**Comment by evansd** [comment]
### Notes on currently defined measures (as of 2022-11-15)

The vast majority of measure definitions use `population` as the denominator.

There are a handful which use some other boolean expression which identifies a subset of the population, and where the numerator is a further subset of the denominator population:
 * https://github.com/opensafely/opioids-covid-research/blob/23c97e4a2c388d7b65dd2819172cf584ee39f501/analysis/study_definition.py
 * https://github.com/opensafely/vacc-trial-monitoring-research/blob/c5c64d44b31581ff288bc1b1b00dbac52e11686d/analysis/study_definition.py
 * https://github.com/opensafely/carehome-noncarehome-death-research/blob/64e31e34d4e0a4936dcf941e9dd6eb9d5ff76ef1/analysis/study_definition_measures.py
 * https://github.com/opensafely/carehome-noncarehome-death-research/blob/64e31e34d4e0a4936dcf941e9dd6eb9d5ff76ef1/analysis/study_definition_comorbidities.py
 * https://github.com/opensafely/asthma_indicators_qof/blob/6f1f4071a8fb962b28c8a9df4c13525be6cec1c3/analysis/study_definition_ast007.py

I found one definition where the denominator (`at_risk`) was a subset of the population, but the numerator was not a subset of the denominator:
 * https://github.com/opensafely/renal-short-data-report/blob/db70482143340844f2eec6de232e315cba8a7c5f/analysis/study_definition.py

There are also a couple of studies which use event counts rather than patient counts as their denominator:
 * https://github.com/opensafely/antimicrobial-stewardship/blob/128809d48d33118431f8a87739781eafacc4caac/analysis/measures.py
 * https://github.com/opensafely/antimicrobial-stewardship/blob/128809d48d33118431f8a87739781eafacc4caac/analysis/study_definition.py
 * https://github.com/opensafely/amr-uom-brit/blob/0c2b78fbf7eca058659a46bf025dd714813cc1ce/analysis/study_definition_broad_comparison.py
 * https://github.com/opensafely/amr-uom-brit/blob/a009517a7311a17be336ea8a844c6de4df9692b2/analysis/study_definition_uti_ab_check_19.py
 * https://github.com/opensafely/amr-uom-brit/blob/3207aecb9f5cfc02f5bdd59e8d6d9d95a04d570a/analysis/study_definition_uti_ab_check_oc.py
 * https://github.com/opensafely/amr-uom-brit/blob/a6cec6003d4381cde621a8b8eede9201b8b66fd6/analysis/study_definition_uti_ab_check_op.py
 * https://github.com/opensafely/amr-uom-brit/blob/243c817f148ab255e35818273c8e3a8d00edf56a/analysis/study_definition_uti_ab_check.py
