### ISSUE TITLE
Implement QOF indicators for diabetes with ehrQL

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#849]
* [GitHub Repo](https://github.com/opensafely/qof-diabetes)
* [Project proposal](https://docs.google.com/document/d/1tKEIdslLm66ozhmhPVRbKARXxm9nie4qWU6ak7jQyRo/edit)
* [QOF indicators](https://docs.google.com/document/d/1_CBq9x2eom9aehERf7ZIH6JU53YNkz8G/edit?rtpof=true&sd=true)
* [Slack](https://bennettoxford.slack.com/archives/C03GWV1QL0K/p1669982591549319)

**Comment by inglesp** [comment]
@milanwiedemann dataset definitions can now be parameterised (https://github.com/opensafely-core/databuilder/pull/1017).  Could you have a go at making use of them here?

**Comment by milanwiedemann** [comment]
- implement measures 
- consider writing project.yaml using Will's _pipeline functions_  (see [here](https://github.com/wjchulme/osutils/pull/3))

**Comment by milanwiedemann** [comment]
@inglesp we should review this issue, the translation of the QOF rules into ehrQL is done. but as mentioned yesterday, I think we should use this project for exploring the ehrQL assurance testing ideas

**Comment by inglesp** [comment]
Fine -- suggest closing this issue and making a new one to cover assurance.

**Comment by inglesp** [comment]
If you're happy to keep working on it, then I think we should.

**Comment by milanwiedemann** [comment]
closing this, assurance work will be documented and tracked elsewhere. Caroline and Alex are picking up some of the diabetes work as their first ehrQL studies
