### ISSUE TITLE
Document creation of dummy data via Data Builder

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/ehrql#975]

**Comment by StevenMaude** [comment]
Moved from opensafely/documentation#1036.

**Comment by iaindillingham** [comment]
I'd suggest adding a new how-to guide to the "[How-to guides](https://docs.opensafely.org/ehrql/how-to/)" section. My preference would be for each guide to have the title "How to `[thing]`". That's inconsistent with the two existing how-to guides, although won't be after #1625 and #1622.

@StevenMaude linked to the GitHub docs "[Style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)" page awhile ago. I've found it really useful when reworking the ehrQL tutorial. If nothing else, it tells you why I've developed a thing for quoting page titles 🙂
